// Empty Component-preload.js file to prevent 404 errors during development
// This file is automatically generated during build process
// For development, we use individual module loading

sap.ui.predefine("eshm/Component", [], function() {
    "use strict";
    // This is a placeholder to prevent 404 errors
    // The actual Component.js will be loaded separately
});

// Register the component preload
sap.ui.loader.config({
    paths: {
        "eshm": "./"
    }
});